name: "Label Checker v3"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-that-label:
    name: La cuenta por favor
    runs-on: ubuntu-latest
    steps:
      - name: Script Label Checker
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.PACKAGES_ACCESS_TOKEN}}
          script: |
            console.log({ context })
            console.log({
              repository: context.payload.repository
            })
            const { sha } = context.payload.pull_request.head
            console.log({ sha })

#            github.repos.createCommitStatus({})
