name: "Label Checker v3"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-that-label:
    name: La cuenta por favor
    runs-on: ubuntu-latest
    steps:
      - name: Script Label Checker
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.PACKAGES_ACCESS_TOKEN}}
          script: |
            console.log(context.payload.repository)
            if (context.payload.action === 'labeled') {
              console.log({ label: context.payload.label })
            }
            const { sha } = context.payload.pull_request.head
            const { name, owner: { login } } = context.payload.repository
            console.log({
              owner: login,
              repo: name,
              sha,
              state: 'success'
            })

            github.rest.repos.createCommitStatus({
              owner: login,
              repo: name,
              sha: sha,
              state: 'success'
            })
