name: "Handle new comments"
on:
  issue_comment:
    types: [created]
jobs:
  pull-request-comment:
    name: On Pull Request Comment
    if: github.event.issue.pull_request
    runs-on: ubuntu-latest
    outputs:
      labeled: ${{ steps.comment-labeler.outputs.labeled }}
    steps:
      # Adds specified label when comment contains listed keywords
      - name: Comment Labeler
        id: comment-labeler
        uses: Amwam/issue-comment-action@v1.3.1
        with:
          keywords: '["[QA Approved]"]'
          labels: '["qa-approved"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
  check-label:
    name: Is QA Approved
    runs-on: ubuntu-latest
    needs: pull-request-comment
    steps:
      - run: |
          echo "Is this PR Labeled? ${IS_LABELED}"
          echo "needs ${IS_LABELED}"
#          ${IS_LABELED} === true && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
          echo "array of names ${GITHUB_CONTEXT.*.name}"
          echo "contains? ${ contains(GITHUB_CONTEXT.*.name, "qa-approved" )}"
        shell: bash
        env:
          ERROR_MESSAGE: "QA Approved label not found"
          IS_LABELED: ${{needs.pull-request-comment.outputs.labeled}}
          GITHUB_CONTEXT: ${{ toJSON(github.event.issue.labels) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
