name: Notify Slack

on:
  push: # Runs on merge (push) to $branch
    branches:
      - notify-slack
concurrency:
  # Only allow one workflow in the 'main' group to run at a time. Others will queue up
  # https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
  group: main

jobs:
  changed-files:
    name: Changed Files
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$GITHUB_CONTEXT"
          echo Changed files information
          all_files=$(git diff --name-only origin/main... | tr '\n' ' ')
          echo ::set-output name=all-files::$all_files
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
