name: "QA Approved"

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  check-label:
    name: QA Approval
    runs-on: ubuntu-latest
    steps:
      - run: |
          ERROR_MESSAGE="QA Approved label not found"
          ${HAS_QA_LABEL} && (echo "You have the QA approved label" && exit 0) || (echo "::error::${ERROR_MESSAGE}" && exit 1)
        shell: bash
        env:
          GITHUB_LABELS: ${{ toJSON(github.event.pull_request.labels.*.name) }}
          HAS_QA_LABEL: ${{ contains(toJSON(github.event.pull_request.labels.*.name), 'qa-approved') }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
