name: "QA Approved"

on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  check-label:
    name: QA Approval
    runs-on: ubuntu-latest
    steps:
      - run: |
          ERROR_MESSAGE="QA Approved label not found"
          echo "check env"
        shell: bash
        env:
          # GITHUB_LABELS: ${{ toJSON(github.event.issue.labels.*.name) }}
          GITHUB_LABELS: ${{ toJSON(github.event) }}
